POST {{host}}/runtime/process-instances
Content-Type: application/json

{
  "processDefinitionKey": "综合流程测试",
  "variables": [
  {
    "name": "id",
    "type": "integer",
    "value": 2,
    "scope": "GLOBAL"
  }
]
}
> {% client.global.set("process-instances-id", response.body.id); %}

###
GET {{host}}/runtime/process-instances/{{process-instances-id}}/variables
