version: '3.6'

services:

  flowable-ui:
    image: flowable/flowable-ui
    container_name: flowable-ui
    hostname: flowable-ui
    ports:
      - 9001:8080
    environment:
      TZ: "Asia/Shanghai"
      SERVER_PORT: 8080
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.h2.Driver
      SPRING_DATASOURCE_URL: jdbc:h2:~/flowable;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: flowable
      SPRING_DATASOURCE_PASSWORD: flowable
      FLOWABLE_COMMON_APP_IDM-URL: http://host.docker.internal:8080/flowable-idm
      FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: http://host.docker.internal:8080/flowable-idm

  flowable-rest:
    image: flowable/flowable-rest
    container_name: flowable-rest
    hostname: flowable-rest
    ports:
      - 9002:8080
    environment:
      TZ: "Asia/Shanghai"
      SERVER_PORT: 8080
      FLOWABLE_REST_APP_ADMIN_USER-ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
      FLOWABLE_REST_APP_ADMIN_FIRST-NAME: Rest
      FLOWABLE_REST_APP_ADMIN_LAST-NAME: Admin

